name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - main
      - fase3-devsecops
  pull_request:
    branches:
      - main

jobs:

  gitleaks:
    name: Secret Scanning - Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  semgrep:
    name: SAST - Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep OWASP and Node.js rules
        run: |
          semgrep scan \
            --config p/javascript \
            --config p/nodejs \
            --config p/expressjs \
            --error .


  trivy:
    name: SCA - Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'vuln'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'